version: '3.8'

services:
  web-app:
    build:
      context: ./service
      dockerfile: Dockerfile.prod
    command: gunicorn service.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web-app/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - database

  database:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  redis:
    image: redis:7.0.5-alpine
    hostname: redis

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web-app/staticfiles
    ports:
      - 80:80
    depends_on:
      - web-app

volumes:
  postgres_data:
  static_volume: