services:
  web-app:
    build:
      context: ./service
    ports:
      - "8000:8000"
    volumes:
      - ./service:/service
    env_file:
      - ./.env.dev
    
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    env_file:
      - ./.env.prod.db

  redis:
    image: redis:7.0.5-alpine
    hostname: redis
