services:
  web-app:
    build:
      context: ./service
    ports:
      - "8000:8000"
    volumes:
      - ./service:/service
    env_file:
      - ./.env.dev
    
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    env_file:
      - ./.env.prod.db

  redis:
    image: redis:7.0.5-alpine
    hostname: redis

  worker:
    build:
      context: ./service
    hostname: worker
    env_file:
      - ./.env.dev
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./service:/service
    links:
      - redis
    depends_on:
      - redis
      - database
    
  flower:
    build:
      context: ./service
    hostname: flower
    env_file:
      - ./.env.dev
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
      - ./service:/service
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"
