# Generated by Django 3.2.16 on 2024-06-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.SmallIntegerField(blank=True, null=True, unique=True)),
                ('character_name', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('character_info', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
            },
        ),
        migrations.CreateModel(
            name='KeyMoves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(blank=True, max_length=20, null=True)),
                ('move_number', models.SmallIntegerField(blank=True, null=True)),
                ('move_name', models.CharField(blank=True, max_length=30, null=True)),
                ('move_input', models.TextField(blank=True, null=True)),
                ('move_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Move',
                'verbose_name_plural': 'Key Moves',
            },
        ),
        migrations.CreateModel(
            name='MoveList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(blank=True, max_length=20, null=True)),
                ('move_name', models.CharField(blank=True, max_length=30, null=True)),
                ('move_input', models.CharField(blank=True, max_length=30, null=True)),
                ('move_type', models.CharField(blank=True, max_length=20, null=True)),
                ('move_level', models.CharField(blank=True, max_length=15, null=True)),
                ('damage', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('block_damage', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('start_up', models.SmallIntegerField(blank=True, null=True)),
                ('active', models.SmallIntegerField(blank=True, null=True)),
                ('recover', models.SmallIntegerField(blank=True, null=True)),
                ('block_adv', models.SmallIntegerField(blank=True, null=True)),
                ('hit_adv', models.SmallIntegerField(blank=True, null=True)),
                ('cancel', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Move',
                'verbose_name_plural': 'Move List',
            },
        ),
        migrations.CreateModel(
            name='OptimalCombos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(blank=True, max_length=20, null=True)),
                ('combo_number', models.SmallIntegerField(blank=True, null=True)),
                ('combo_name', models.CharField(blank=True, max_length=30, null=True)),
                ('combo_input', models.TextField(blank=True, null=True)),
                ('combo_bars', models.SmallIntegerField(blank=True, null=True)),
                ('side_switch', models.BooleanField(blank=True, null=True)),
                ('corner', models.BooleanField(blank=True, null=True)),
                ('difficulty', models.SmallIntegerField(blank=True, null=True)),
                ('combo_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tip',
                'verbose_name_plural': 'Tips & Combos',
            },
        ),
    ]
