# Generated by Django 3.2.16 on 2024-08-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterlist',
            name='character_name',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='movelist',
            name='character_name',
            field=models.CharField(blank=True, default='Someone', max_length=20),
        ),
        migrations.AlterField(
            model_name='movelist',
            name='move_name',
            field=models.CharField(blank=True, default='Some Move', max_length=30),
        ),
        migrations.AlterField(
            model_name='optimalcombos',
            name='character_name',
            field=models.CharField(blank=True, default='Some', max_length=20),
        ),
        migrations.AlterField(
            model_name='optimalcombos',
            name='combo_name',
            field=models.CharField(blank=True, default='Some', max_length=30),
        ),
    ]
